[window]
title = "Alacritty"
padding.x = 45
padding.y = 40

[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = false

[general]
live_config_reload = true
working_directory = "None"

import = [ "/home/harsh/.config/alacritty/colors.toml" ]

[font]
size = 15
normal = { family = "GeistMono Nerd Font Propo", style = "Bold" }
offset =  { x = 0, y = 2}

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"
