source = ~/.config/hypr/colors.conf

# BACKGROUND
background {
    path = ~/Pictures/Wallpapers/v1.png
    blur_passes = 3
    contrast = 0.9
    brightness = 0.5
    vibrancy = 0.17
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%a, %d %B")"
    color = $onSurface
    font_size = 25
    font_family = Rubik
    position = 50, 450
    halign = left
    valign = center
}

# Time (Hours)
label {
    monitor =
    text = cmd[update:1000] date +"%H"
    color = $primary
    font_size = 150
    font_family = Neue Machina Ultrabold
    position = 0, 160
    halign = center
    valign = center
}

# Time (Minutes)
label {
    monitor =
    text = cmd[update:1000] date +"%M"
    color = $on_surface
    font_size = 150
    font_family = Neue Machina Ultrabold
    position = 0, -20
    halign = center
    valign = center
}


# USER
label {
    monitor =
    text =
    color = rgba(216, 222, 233, 0.80)
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    font_size = 18
    font_family = RadioCanadaBig
    position = 0, -130
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = $primary_fixed_dim
    inner_color = $on_primary_container
    font_color = $surface_container_low
    fade_on_empty = true
    font_family = DM Sans
    placeholder_text = Enter Password...
    hide_input = false
    position = 0, -310
    halign = center
    valign = center
}


